JobsityChat/JobsityChat.Web/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using JobsityChat.Business.Services.Interfaces;
using JobsityChat.Data.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace JobsityChat.Web.Controllers
{
    public class AccountController : Controller
    {
        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;
        
        public AccountController(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            _signInManager = signInManager ?? throw new ArgumentNullException(nameof(signInManager));
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LoginAsync(string username, string password)
        {
            var user = await _userManager.FindByNameAsync(username);
            if (user != null)
            {
                var result = await _signInManager.PasswordSignInAsync(user, password, false, false);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Chat");
                }
            }

            return RedirectToAction("Login", "Account");
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RegisterAsync(string username, string password)
        {
            var user = new User
            {
                UserName = username
            };

            var result = await _userManager.CreateAsync(user, password);

            if (result.Succeeded)
            {
                await _signInManager.SignInAsync(user, false);

                return RedirectToAction("Index", "Chat");
            }
            
            return RedirectToAction("Register", "Account");
        }

        [HttpGet]
        public async Task<IActionResult> LogoutAsync()
        {
            await _signInManager.SignOutAsync();

            return RedirectToAction("Login", "Account");
        }
    }
}

JobsityChat/JobsityChat.Web/Controllers/ChatController.cs
using System;
using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;
using JobsityChat.Business.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JobsityChat.Web.Controllers
{
    [ApiController]
    [Route("[controller]")]
    [Authorize]
    public class ChatController : Controller
    {
        private readonly IChatService _chatService;

        public ChatController(IChatService chatService)
        {
            _chatService = chatService ?? throw new ArgumentNullException(nameof(chatService));
        }

        public async Task<IActionResult> Index(CancellationToken cancellationToken = default)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            return View(await _chatService.GetRoomsForIndexAsync(userId, cancellationToken));
        }

        [HttpGet]
        [Route("GetRoomAsync/{id}")]
        public async Task<IActionResult> GetRoomAsync(int id, CancellationToken cancellationToken = default)
        {
            var room = await _chatService.GetRoomAsync(id, cancellationToken);

            return View("Chat", room);
        }

        [HttpPost]
        [Route("CreateRoomAsync")]
        public async Task<IActionResult> CreateRoomAsync([FromForm]string name, CancellationToken cancellationToken = default)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await _chatService.CreateRoomAsync(name, userId, cancellationToken);
            
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("[action]/{connectionId}/{roomName}")]
        public async Task<IActionResult> JoinRoom(string connectionId, string roomName, CancellationToken cancellationToken = default)
        {
            await _chatService.JoinRoomAsync(connectionId, roomName, cancellationToken);

            return Ok();
        }

        [HttpPost]
        [Route("[action]/{connectionId}/{roomName}")]
        public async Task<IActionResult> LeaveChat(string connectionId, string roomName, CancellationToken cancellationToken = default)
        {
            await _chatService.LeaveRoomAsync(connectionId, roomName, cancellationToken);

            return Ok();
        }
    }
}

JobsityChat/JobsityChat.Web/Controllers/ChatUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;
using JobsityChat.Business.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JobsityChat.Web.Controllers
{
    [ApiController]
    [Route("[controller]")]
    [Authorize]
    public class ChatUserController : Controller
    {
        private readonly IChatUserService _chatUserService;
        public ChatUserController(IChatUserService chatUserService)
        {
            _chatUserService = chatUserService ?? throw new ArgumentNullException(nameof(chatUserService));
        }

        [HttpGet]
        [Route("JoinRoomAsync/{id}")]
        public async Task<IActionResult> JoinRoomAsync(int id, CancellationToken cancellationToken = default)
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await _chatUserService.JoinRoomAsync(id, userId, cancellationToken);
            
            return RedirectToAction("GetRoomAsync", "Chat", new { id = id });
        }
    }
}

JobsityChat/JobsityChat.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JobsityChat.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return RedirectToAction("Index", "Chat");
        }
    }
}

JobsityChat/JobsityChat.Web/Controllers/MessageController.cs
using System;
using System.Threading;
using System.Threading.Tasks;
using JobsityChat.Business.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JobsityChat.Web.Controllers
{
    [ApiController]
    [Route("[controller]")]
    [Authorize]
    public class MessageController : Controller
    {
        private readonly IMessageService _messageService;
        public MessageController(IMessageService messageService)
        {
            _messageService = messageService ?? throw new ArgumentNullException(nameof(messageService));
        }

        [HttpPost]
        [Route("[action]")]
        public async Task<IActionResult> SendMessage([FromForm] int chatId, [FromForm] string message, [FromForm] string roomName, CancellationToken cancellationToken = default)
        {
            var user = User.Identity.Name;

            await _messageService.SendMessage(chatId, message, roomName, user, cancellationToken);

            return Ok();
        }

    }
}

JobsityChat/JobsityChat.Web/ViewComponents/ChatViewComponent.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using JobsityChat.Data.Repositories.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace JobsityChat.Web.ViewComponents
{
    public class ChatViewComponent : ViewComponent
    {
        private IChatUserRepository _chatUserRepository;

        public ChatViewComponent(IChatUserRepository chatUserRepository)
        {
            _chatUserRepository = chatUserRepository ?? throw new ArgumentNullException(nameof(chatUserRepository));
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var chats = await _chatUserRepository.Get()
                .Include(x => x.Chat)
                .Where(x => x.UserId == userId)
                .Select(x => x.Chat)
                .ToListAsync();

            return View(chats);
        }
    }
}

JobsityChat/JobsityChat.Web/Views/Chat/Chat.cshtml
@model Chat

<div class="chat-body">
    @foreach (var message in Model.Messages)
    {
        <div class="message">
            <header>@message.Name:</header>
            <p>@message.Text</p>
            <footer>@message.Timestamp</footer>
        </div>
    }
</div>

<form class="chat-input" onsubmit="sendMessage(event)">
    <input type="hidden" name="chatId" value="@Model.Id">
    <input type="hidden" name="roomName" value="@Model.Name">
    <input type="text" name="message" id="message-input">
    <button type="submit">Send</button>
</form>

@section scripts {
    <script src="~/scripts/signalr.min.js"></script>
    <script src="~/scripts/messageBuilder.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

    <script>
        var connection = new signalR.HubConnectionBuilder()
            .withUrl("/chatHub")
            .build()

        var _connectionId = '';

        connection.on("RecieveMessage", function (data) {
            var message = messageBuilder()
                .createMessage()
                .withHeader(data.name)
                .withParagraph(data.text)
                .withFooter(data.timestamp)
                .build();

            document.querySelector('.chat-body').append(message);
        })

        var joinRoom = function () {
            var url = '/Chat/JoinRoom/' + _connectionId + '/@Model.Name';
            console.log(url);
            axios.post(url, null)
                .then(res => {
                    console.log("Room Joined!", res);
                })
                .catch(err => {
                    console.log("Failed to join Room!", err);
                })
        }

        connection.start()
            .then(function() {
                connection.invoke('getConnectionId')
                    .then(function (connectionId) {
                        _connectionId = connectionId
                        joinRoom();
                    })
            })
            .catch(function (err) {
                console.log(err);
            })

        var sendMessage = function (event) {
            event.preventDefault();
            var data = new FormData(event.target);
            document.getElementById('message-input').value = '';

            axios.post('/Message/SendMessage', data)
                .then(res => {
                    console.log("Message sent!");
                })
                .catch(err => {
                    console.log("Error sending message");
                })
        }

    </script>
}

JobsityChat/JobsityChat.Web/Views/Chat/Index.cshtml
@model IEnumerable<Chat>

<div class="chat-body">
    @foreach (var chat in Model)
    {
        <a class="room-button" asp-controller="ChatUser" asp-action="JoinRoomAsync" asp-route-id="@chat.Id">
            @chat.Name
        </a>
    }

</div>

JobsityChat/JobsityChat.Web/Views/Shared/Components/Chat/Default.cshtml
@model IEnumerable<Chat>

<div class="side-menu">
    @foreach (var chat in Model)
    {
        <a class="room-button" asp-controller="Chat" asp-action="GetRoomAsync" asp-route-id="@chat.Id">
            @chat.Name
        </a>
    }

    <a class="room-button" id="create-room-btn" href="#">
        <strong>+</strong>
    </a>
</div>

JobsityChat/JobsityChat.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Jobsity Chat</title>

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="navbar">
        <a asp-controller="Home" asp-action="Index">Inicio</a>
    </div>
    <div class="main">
        @if (User.Identity.IsAuthenticated)
        {
            <vc:chat></vc:chat>
        }
        <div class="chat">
            @RenderBody()
        </div>
    </div>

    <div class="modal" id="create-room-modal">
        <form asp-controller="Chat" asp-action="CreateRoomAsync" class="modal-body">
            <button type="button" class="close" onclick="closeModal()">X</button>
            <header>Create Room</header>
            <div>
                <input name="name">
            </div>
            <footer>
                <button>Create</button>
            </footer>
        </form>
    </div>

    <script src="~/scripts/site.js"></script>
    @RenderSection("scripts", false)

</body>
</html>